apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-spring
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: test
      taskRef:
        name: catalyst-spring-boot-test-task
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: build-image
      taskRef:
        name: build-ibm-cloud-image
      runAfter: [test]
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: generate-helm-chart
      taskRef:
        name: generate-helm-chart
      runAfter: [build-image]
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: helm-package
      taskRef:
        name: helm-package
      runAfter: [generate-helm-chart]
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: health-check
      taskRef:
        name: health-check
      runAfter: [helm-package]
      resources:
        inputs:
          - name: source
            resource: git-source
    - name: gitops
      taskRef:
        name: gitops
      runAfter: [health-check]
      resources:
        inputs:
          - name: source
            resource: git-source
